#!/bin/bash

# A script could be made to automate the build process,
# provided that IL2CPP and Mono can be switched through code
# Then, builds for all platforms could be made just by running this script

# TODO: Only building for Linux works (presumably because of IL2CPP)

cd ..
unityPath=\
"$HOME/.unity/\
$(cat './ProjectSettings/ProjectVersion.txt' | grep 'm_EditorVersion:' | sed 's/.*\: //g')\
/Editor/Unity"
echo $unityPath

tail -f ~/.config/unity3d/Editor.log &
processID=$!
$unityPath \
  -logFile "$HOME/.config/unity3d/Editor.log" \
  -quit \
  -batchmode \
  -projectPath "$(pwd)" \
  -executeMethod AutoBuild.Build "$@" ;\
  kill $processID || {
    echo "Build failed!";
    exit 2;
  }

cd -
