#!/bin/bash
butlerBin="../Assets_Excluded/butler-linux-amd64/butler"

echo "Pushing Linux build..."
$"$butlerBin" push Keyflow-Linux-x64.zip namelesshorseman/keyflow:linux
echo "Pushing MacOS build..."
$"$butlerBin" push Keyflow-Mac-ARM+x64.zip namelesshorseman/keyflow:macos
echo "Pushing Windows build..."
$"$butlerBin" push Keyflow-Windows-x64.zip namelesshorseman/keyflow:windows
